### ISSUE TITLE
mysql update 同步异常

### ISSUE THREAD

**Issue by WeiZhixiong** [m358807551/mysqlsmom#18]
mysql  表中部分字段更新，会造成 mysqlsmom 异常，无法继续执行。
sql ： 
`update tb_emp set message="update" where id=20190715101404;`
error：
`elasticsearch.exceptions.RequestError: RequestError(400, u'action_request_validation_exception', u'Validation Failed: 1: id is missing;')`

**Comment by m358807551** [comment]
同步方式是什么呢？
