### ISSUE TITLE
配置好，然后运行一段时间后报Killed

### ISSUE THREAD

**Issue by luyaotang** [m358807551/mysqlsmom#21]
ElasticSearch用的是最新的 7.4
安装时没有这个选择，就选择了
pip install --upgrade elasticsearch==7.1.0
mom new test_mom/init_config.py -t init --force
vim ./test_mom/init_config.py  # 按注释提示修改配置
执行一段时间，大概几分钟，然后就报Killed,什么信息都没有。
[root@luyaodev local]# mom run -c ./test_mom/init_config.py
Killed
[root@luyaodev local]#

**Comment by m358807551** [comment]
只支持 es6及以下版本，见谅~
