### ISSUE TITLE
mysqlsmom 手动运行  没多久就自动停了 

### ISSUE THREAD

**Issue by codech** [m358807551/mysqlsmom#25]
mysqlsmom 手动运行  没多久就自动停了  没有日志 也没有报错

**Comment by m358807551** [comment]
这个是 mysqlsmom 的bug，如果还在凑活着用的话，可以用 supervisor 启动 myslqsmom，在myslqsmom挂了的时候能自动拉起~

**Comment by codech** [comment]
哥们这个是不维护了吗

m358807551 ***@***.***> 于2022年1月6日周四 15:55写道：

**Comment by m358807551** [comment]
是的已经不维护了
