### ISSUE TITLE
请求开发python3的版本

### ISSUE THREAD

**Issue by shixiaobo8** [m358807551/mysqlsmom#27]
pypi 上面已经删掉这个包了 找不到了 ,源码包clone 下来python setup.py install 也报各种2.7的错误  能不能开发python3 的版本

**Comment by shixiaobo8** [comment]
这个报之前用的还不错,一直再用,后来想安装发现 pypi 下架了

**Comment by shixiaobo8** [comment]
就前几天下架的

**Comment by m358807551** [comment]
实在是不好意思，我最近被裁员了..... 比较焦虑，现在才回复...
0. 首先这个包在 pypi上还是存在的:  https://pypi.org/project/mysqlsmom/，在python2.7环境下执行 `pip install mysqlsmom` 是可以下载的，我刚测试过~
1. 目前也没精力支持python3了..见谅，但是通过 conda 等工具可以轻松制造出一个 Python2.7的环境来~ 可以在该环境下使用

**Comment by shixiaobo8** [comment]
大神继续加油~~!

**Comment by m358807551** [comment]
一起加油，奥利给
