### ISSUE TITLE
中文字段使用ik插件进行分词

### ISSUE THREAD

**Issue by victory-hsu** [m358807551/mysqlsmom#28]
您好，请问一下做这个在哪里修改代码，修改mapping设置，使得某中文字段在ik分词插件下构建索引，并进行搜索？

比如：我的question字段需要设置：
  "question": {
                  "type": "text",
                  "analyzer": "ik_smart",
                  "search_analyzer": "ik_max_word",
              }

但是我再代码目录结构中没有找到添加的地方

期待作者的回复，谢谢！！！

**Comment by m358807551** [comment]
Hi，你需要在elasticsearch创建index的时候，在mappings里先设置好字段的分词方式，mysqlsmom只负责同步数据 ：）
