### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by robblecrunch** [m358807551/mysqlsmom#7]
您好，我们计划使用您的这个工具同步mysql和es。使用中想完成这些功能：
1､初始化，针对大表，实现区间查询；
2､针对增量，时间辍不使用上次运行时间，而使用上批数据最大时间。并支持："select id, name from person where update_time >= ?"
 ->"select id, name from person where update_time >= ? and _id > ?"

即记录的上次增量的最大时间辍及主键id（我们有些场景，偶尔少量一微秒更新几十万数据）。这样更新大量数据，也可一次取只定条数，并记录本次更新到哪个时间辍和记录id。
3､支持嵌套查询
4､增量模式支持delete

您看，是否有计划完成这些功能？或者我们增加向你提交也行。

**Comment by m358807551** [comment]
非常感谢反馈~ 

1、针对大表的全量同步，已经用到了一些压缩内存的技术，但对于某些过大的表，内存撑不住还是会崩溃。区间同步是锦上添花的事~  换个大点内存的机器或者像下面这样多同步几次总能同步完，另外初始化也可以用logstash、filebeat或其它工具， 初始化时对大表应该做了比较好的优化。
```
TASKS = [
    {
        "stream": {
            "database": "my_db",
            "sql": "select * from my_table order by id limit 100000",
        },
       "jobs": [...]
   },
  {
        "stream": {
            "database": "my_db",
            "sql": "select * from my_table order by id limit 100000,100000",
        },
       "jobs": [...]
   },
  ...
```

2、一微秒更新几十万条数据... 我有点虚啊，Mysqlsmom毕竟只有一个人开发，一秒10万条数据都没有测试过... 并且根据时间戳的增量同步目前还是有一些问题，比如同步失败后会一直重试可能造成对数据库的压力等。实时的增量同步还是推荐基于binlog的那种，不过你们要求的QPS太大... 还是考虑一下更新

3、能举个含嵌套查询的例子吗？

4、基于binlog的增量同步是可以支持delete的，详情见文档。

Mysqlsmom 处于刚刚满足我们公司业务需求的阶段，除非非做不可否则不计划大改..
您可以Fork本项目或Clone项目到本地，进行修改使用，
`mom run -c xxx.py`
等价于 在mysqlsmom.py 文件夹下执行
`python mysqlsmom.py run -c xxx.py`

**Comment by robblecrunch** [comment]
您好， 您说的太对了。我们更新是没有一秒几十万的，是在生产环境曾经发生一次这样的事故，有同事手工更新了几十万条记录，然后我们一个程序依赖时间辍，出了问题。

**Comment by robblecrunch** [comment]
同时，您反馈的：并且根据时间戳的增量同步目前还是有一些问题，比如同步失败后会一直重试可能造成对数据库的压力等

这里给数据库增加压力，具体是哪部分代码？是查询了库，但写redis中的同步点失败吗？

**Comment by robblecrunch** [comment]
135     def upload_docs(self):
136         try:
137             helpers.bulk(es, self.docs)
138         except BulkIndexError, e:
139             for error in e.errors:
140                 if not error.keys()[0] == "delete":
141                     raise e
142                 if not error.values()[0]["found"] == False:
143                     raise e
144         self.docs = []

您说的对数据库造成压力，是因为这里异常失败，会造成对数据库压力大吗？

**Comment by robblecrunch** [comment]
您看这里：
312         md5 = hashlib.md5(config.__name__ + task["stream"]["database"] + task["stream"]["sql"]).hexdigest()

键名，能否不只用md5, 再加name和 database做为前辍，便于排查问题？

**Comment by m358807551** [comment]
你好，根据时间戳的增量同步可能会对数据库造成压力的原因是：根据时间戳取得的数据只有全部同步成功后，时间戳才会更新以便下次取数据。也就是说只要有一条数据同步失败，记录的时间戳就不会更新，随着数据库插入的数据越来越多，定时的 `select * from table where update_time >= 时间戳` 取回的数据会越来越多，对数据库造成压力。当然没有数据同步失败就不会出现该问题；

**Comment by m358807551** [comment]
只用md5确实有些草率...

**Comment by robblecrunch** [comment]
嗯，那我计划修改为：失败 N次后，状态写redis， 必须手工干预才恢复。

**Comment by robblecrunch** [comment]
def raw(sql):

            query = MyModel.raw(MyModel.section).dicts()
            assign = [-1, -1]
            cur = -1

            if query:
                assign = query[0].values()
                assign.sort()
                cur = assign[1] + 1

            while  cur > assign[0]:

                sql = sql.replace('$END', '%d' %  cur)
                last = cur
                cur = cur - MyModel.sql_range_step
                if cur < assign[0]:
                    cur = assign[0]
                sql = sql.replace('$START', '%d' % cur)

                yield MyModel.raw(sql).dicts()



        for query in raw(task["stream"]["sql"]):

**Comment by robblecrunch** [comment]
区间查询我做了一个版本。

**Comment by robblecrunch** [comment]
昨天我试了一个2000万记录的表。iterator时，出第一条记录，耗时47分钟。
