### ISSUE TITLE
程序不再读取binlog日志

### ISSUE THREAD

**Issue by llwwlql** [m358807551/mysqlsmom#9]
binlog记录一直卡在：100105408位置，日志也不再打印，也没有报错，持续这个状态很久了，数据库中的binlog位置已经到了126084862。重启程序后也没有任何变化，没有任何日志打印，不知道该如何排查该问题

**Comment by m358807551** [comment]
你好，知道哪些数据没有同步吗？
知道的话，先停止同步进程，把redis里记录binlog位置和文件的两个key清除掉，再启动进程，理论上新的数据会正常同步（保险起见先保存一下这两个key和值），再通过全量同步同步少的数据呢。
另：之前的binlog同步有延时吗？redis里存的读取的binlog文件确实还存在吗？

**Comment by llwwlql** [comment]
嗯，有试过清掉redis里面key，重启程序，没有效果。这边看到起来程序，redis里面的pos并没有更新，正常跑的程序那个数据是在不断更新的。binlog同步有延时的。

**Comment by m358807551** [comment]
log_file 和 log_pos 这两个结尾的key都清除了吗

**Comment by llwwlql** [comment]
都清除掉了，一样卡在那里的
